### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by mml1** [davidmikulis/tea-cozy#1]
Great job having a folder for images! However, I would suggest having a folder called resources and adding both your img folder and style.css in there. So, your project structure would look something like:

tea-cozy
-index.html
-resources
--style.css
--img

https://github.com/davidmikulis/tea-cozy

**Comment by davidmikulis** [comment]
Noted, and thank you. The index.html should remain by itself at the top level and the CSS should be included with the rest of the resources.
