### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by mml1** [davidmikulis/tea-cozy#2]
Fantastic job having comments! Your comments are very descriptive maybe too descriptive. There is a certain balance with comments. You could do without the following lines:

https://github.com/davidmikulis/tea-cozy/blob/master/style.css#L14-L17
https://github.com/davidmikulis/tea-cozy/blob/master/style.css#L42-L44
https://github.com/davidmikulis/tea-cozy/blob/master/style.css#L109-L111
https://github.com/davidmikulis/tea-cozy/blob/master/style.css#L150-L152

**Comment by davidmikulis** [comment]
Thank you! On the first project I received feedback that I had too few comments, so I may have gone too far on this project to compensate.
