### ISSUE TITLE
Alternative font family missing

### ISSUE THREAD

**Issue by mml1** [davidmikulis/tea-cozy#3]
Remember to have an alternative font-family, just in case the font is not available to your user.

**Change**
`font-family: Helvetica;
`
**to**
`font-family: "Helvetica", sans-serif;`

https://github.com/davidmikulis/tea-cozy/blob/master/style.css#L7

**Comment by davidmikulis** [comment]
Something I hadn't considered. I'm not sure how font availability works (is it browser-dependent?) but I hadn't considered the possibility of a font not being available. So I suppose it would default to the next font if the first one is not available, I'll make sure to include that going forward.
