### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [davidmikulis/tea-cozy#4]
[Exceeds Expectations] Fantastic work!

**Great work with:**
- Using flexbox
- Consistent indentation
- Descriptive class/id names
- Descriptive comments
- Relative link usage
- Storing images locally
- Div usage
- Alt tag usage
- Whitespace usage

**Improve the following:**
- Using less comments
- Project structure
- Adding alternative font-families

**Subjects to research:**
- media queries
- rem
- 2 vs 4 spaces for indentation

Overall, great job! 👍

**Comment by davidmikulis** [comment]
Thank you for the review! I am excited to continue learning and improving.
